# Generated by Django 5.1.6 on 2025-03-24 12:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Composicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.ingrediente')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='cadastro.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('numero_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_entrega', models.IntegerField(choices=[(1, 'Entrega'), (2, 'Retirada'), (3, 'Consumo no local')])),
                ('observacao_pedido', models.TextField(blank=True, null=True)),
                ('situacao_do_pedido', models.CharField(max_length=2)),
                ('quantidade', models.DecimalField(decimal_places=5, default=0, max_digits=14)),
                ('quantidade_aberta', models.DecimalField(decimal_places=5, default=0, max_digits=14)),
                ('valor_pedido', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('data_aprovacao_pedido', models.DateField(blank=True, null=True)),
                ('hora_aprovacao_pedido', models.TimeField(blank=True, null=True)),
                ('data_inicio_pedido', models.DateField(default=django.utils.timezone.now)),
                ('hora_inicio_pedido', models.TimeField(default=django.utils.timezone.now)),
                ('data_fim_pedido', models.DateField(blank=True, null=True)),
                ('hora_fim_pedido', models.TimeField(blank=True, null=True)),
                ('data_geracao', models.DateField(default=django.utils.timezone.now)),
                ('hora_geracao', models.TimeField(default=django.utils.timezone.now)),
                ('cliente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cadastro.cliente')),
                ('forma_de_pagamento', models.ForeignKey(db_column='forma_de_pagamento_id', on_delete=django.db.models.deletion.CASCADE, to='cadastro.formapagamento')),
                ('usuario_gerador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_pedida', models.DecimalField(decimal_places=5, default=1, max_digits=14)),
                ('quantidade_aberta', models.DecimalField(decimal_places=5, default=1, max_digits=14)),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('eh_marmita', models.BooleanField(default=False)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='pedido.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.produto')),
            ],
        ),
        migrations.CreateModel(
            name='PedidoItemComposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=5, max_digits=14)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.ingrediente')),
                ('pedido_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composicoes', to='pedido.pedidoitem')),
            ],
        ),
    ]
