# Generated by Django 5.1.6 on 2025-03-27 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_tituloreceber_titulomovimento_titulohistorico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Caixa',
            fields=[
                ('data_caixa', models.DateField(primary_key=True, serialize=False)),
                ('data_abertura', models.DateTimeField(auto_now_add=True)),
                ('data_fechamento', models.DateTimeField(blank=True, null=True)),
                ('data_proximo_caixa', models.DateField(blank=True, null=True)),
                ('moeda', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bancos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cartoes', models.IntegerField(default=0)),
                ('cartoes_credito', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cartoes_credito_operacao_0', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cartoes_credito_operacao_1', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cartoes_credito_operacao_2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('adiantamentos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('despesas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_despesas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('receitas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_receitas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('saldo_atual', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('situacao', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1)),
                ('usuario_fechamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL)),
                ('usuarios_abertura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
