# Generated by Django 5.1.6 on 2025-03-31 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_caixa'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caixa',
        ),
    ]
