# Generated by Django 5.1.6 on 2025-09-05 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='tipo',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('VENDEDOR', 'Vendedor'), ('CAIXA', 'Caixa')], default='VENDEDOR', max_length=20),
        ),
    ]
