# Generated by Django 5.1.6 on 2025-08-14 15:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('codigo_agrupamento', models.CharField(blank=True, max_length=20, null=True)),
                ('cor', models.CharField(blank=True, max_length=50, null=True)),
                ('custo_ultimo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('custo_medio', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='produtos/')),
                ('ativo', models.BooleanField(default=True)),
                ('criado_em', models.DateTimeField(default=django.utils.timezone.now)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='produtos.categoria')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.fornecedor')),
                ('tamanho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoCusto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data_custo', models.DateField()),
                ('sequencia', models.IntegerField()),
                ('valor_base', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('perc_frete', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('custo_medio', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('tipo_custo', models.CharField(blank=True, choices=[('M', 'Manual'), ('A', 'Automático')], max_length=1, null=True)),
                ('cod_fornecedor', models.IntegerField(blank=True, null=True)),
                ('numero_nota', models.IntegerField(blank=True, null=True)),
                ('serie_nota', models.CharField(blank=True, max_length=3, null=True)),
                ('seq_item', models.IntegerField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('N', 'Não Processado'), ('C', 'Cancelado'), ('P', 'Processado')], default='N', max_length=1)),
                ('data_geracao', models.DateField(blank=True, null=True)),
                ('hora_geracao', models.IntegerField(blank=True, null=True)),
                ('atualiza_custo_preco', models.CharField(choices=[('S', 'Sim'), ('N', 'Não')], default='S', max_length=1)),
                ('data_alteracao', models.DateField(blank=True, null=True)),
                ('hora_alteracao', models.IntegerField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('valor_frete', models.DecimalField(blank=True, decimal_places=4, max_digits=13, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('usuario_alteracao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_alterados', to=settings.AUTH_USER_MODEL)),
                ('usuario_gerador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_custo'],
                'unique_together': {('produto', 'data_custo', 'sequencia')},
            },
        ),
    ]
