# Generated by Django 5.1.6 on 2025-08-14 15:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produtos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormacaoPreco',
            fields=[
                ('produto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='produtos.produto')),
                ('custo_base', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('valor_custo', models.DecimalField(blank=True, decimal_places=4, max_digits=15, null=True)),
                ('custo_com_frete', models.DecimalField(decimal_places=4, default=0, max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('margem_custo_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_venda_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoPrecoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custo_base', models.DecimalField(decimal_places=4, max_digits=10)),
                ('custo_com_frete', models.DecimalField(decimal_places=4, max_digits=10)),
                ('margem_lucro', models.DecimalField(decimal_places=2, max_digits=5)),
                ('margem_custo_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('valor_venda_sugerido', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_alteracao'],
            },
        ),
        migrations.CreateModel(
            name='TabelaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativa'), ('I', 'Inativa')], default='A', max_length=1)),
                ('data_criacao', models.DateField(auto_now_add=True)),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TabelaPrecoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preco_venda', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Preço de Venda')),
                ('data_inicial', models.DateField(verbose_name='Início da Vigência')),
                ('data_final', models.DateField(blank=True, null=True, verbose_name='Fim da Vigência')),
                ('valor_custo', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Valor do Custo')),
                ('margem_lucro', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Margem de Lucro (%)')),
                ('margem_custo_fixo', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Margem Custo Fixo (%)')),
                ('custo_base', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo Base')),
                ('custo_com_frete', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='Custo com Frete')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produtos.produto')),
                ('tabela_preco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='preco.tabelapreco')),
                ('usuario_criacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tabela_preco_criada', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-data_inicial'],
                'unique_together': {('produto', 'tabela_preco', 'data_inicial')},
            },
        ),
    ]
