# Generated by Django 5.1.6 on 2025-08-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_venda', models.DateTimeField(auto_now_add=True)),
                ('data_liberacao', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('AV', 'À Vista'), ('AP', 'A Prazo')], max_length=2)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_entrada', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_parcelas', models.IntegerField(default=1)),
                ('situacao', models.CharField(choices=[('DI', 'Digitada'), ('FE', 'Fechada'), ('CA', 'Cancelada'), ('EX', 'Excluída'), ('LI', 'Liberada'), ('DE', 'Devolvida')], default='DI', max_length=2)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vendas', to='core.formapagamento')),
            ],
        ),
        migrations.CreateModel(
            name='VendaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='VendaParcela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_parcela', models.PositiveIntegerField(verbose_name='Número da Parcela')),
                ('quantidade_parcelas', models.PositiveIntegerField(verbose_name='Quantidade Total de Parcelas')),
                ('data_vencimento', models.DateField(verbose_name='Data de Vencimento da Parcela')),
                ('valor_parcela', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Parcela')),
                ('situacao', models.CharField(choices=[('A', 'Aberta'), ('P', 'Paga'), ('C', 'Cancelada')], default='A', max_length=1, verbose_name='Situação')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parcelas_venda', to='core.formapagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas_venda', to='vendas.venda')),
            ],
            options={
                'verbose_name': 'Parcela da Venda',
                'verbose_name_plural': 'Parcelas das Vendas',
                'ordering': ['venda', 'numero_parcela'],
            },
        ),
    ]
