# Generated by Django 5.1.6 on 2025-08-21 21:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_estoquemovimento_cliente_estoquemovimento_venda_and_more'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendaitem',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='suprimentos.deposito'),
        ),
    ]
