# Generated by Django 5.1.6 on 2025-08-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('produtos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deposito',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saída'), ('AJ', 'Ajuste')], max_length=2)),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantidade_anterior', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantidade_estoque', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('numero_nota', models.CharField(blank=True, max_length=20)),
                ('serie_nota', models.CharField(blank=True, max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suprimentos.deposito')),
                ('fornecedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='NotaFiscalEntrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=10)),
                ('serie', models.CharField(max_length=5)),
                ('data_emissao', models.DateField()),
                ('data_entrada', models.DateField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('valor_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('observacao', models.TextField(blank=True)),
                ('situacao', models.CharField(choices=[('1', 'Digitada'), ('2', 'Fechada'), ('3', 'Cancelada')], default='1', max_length=1)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.fornecedor')),
            ],
            options={
                'ordering': ['-numero'],
                'unique_together': {('numero', 'serie', 'fornecedor')},
            },
        ),
        migrations.CreateModel(
            name='NotaFiscalEntradaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=12)),
                ('percentual_frete', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_frete_aplicado', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('custo_unitario_calculado', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('aplicar_custo', models.BooleanField(default=False)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suprimentos.deposito')),
                ('nota_fiscal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='suprimentos.notafiscalentrada')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
        ),
        migrations.CreateModel(
            name='Estoque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('deposito', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='suprimentos.deposito')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='produtos.produto')),
            ],
            options={
                'unique_together': {('produto', 'deposito')},
            },
        ),
    ]
