# Generated by Django 5.1.6 on 2025-08-22 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suprimentos', '0002_estoquemovimento_cliente_estoquemovimento_venda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoquemovimento',
            name='numero_nota',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estoquemovimento',
            name='serie_nota',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
