# Generated by Django 5.1.6 on 2025-08-14 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TituloReceber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vencimento', models.DateField()),
                ('data_recebimento', models.DateField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Aberto'), ('R', 'Recebido'), ('C', 'Cancelado')], default='A', max_length=1)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='titulos_receber', to='core.formapagamento')),
                ('venda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titulos', to='vendas.venda')),
            ],
        ),
        migrations.CreateModel(
            name='TituloMovimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('E', 'Entrada'), ('B', 'Baixa')], max_length=1)),
                ('data_movimento', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('situacao', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='A', max_length=1)),
                ('forma_pagamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movimentos_titulo', to='core.formapagamento')),
                ('titulo_receber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movimentos', to='financeiro.tituloreceber')),
            ],
        ),
    ]
