# Generated by Django 5.1.6 on 2025-08-20 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0002_caixa_caixamovimento'),
    ]

    operations = [
        migrations.AddField(
            model_name='tituloreceber',
            name='valor_aberto',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
