# Generated by Django 5.1.6 on 2025-08-20 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0003_tituloreceber_valor_aberto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tituloreceber',
            name='valor_aberto',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
