# Generated by Django 5.1.6 on 2025-08-20 18:47

from django.db import migrations, models
from django.utils import timezone

class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0004_alter_tituloreceber_valor_aberto'),
    ]

    operations = [
        migrations.AddField(
        model_name='caixa',
        name='data_abertura_caixa',
        field=models.DateTimeField(auto_now_add=True, default=timezone.now),
        preserve_default=False,
    ),
        migrations.AddField(
            model_name='caixa',
            name='data_fechamento_caixa',
            field=models.DateTimeField(null=True, blank=True),
            preserve_default=False,
        ),
    ]
