# Generated by Django 5.1.6 on 2025-08-21 20:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0005_caixa_data_abertura_caixa_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixa',
            name='usuario',
        ),
        migrations.AddField(
            model_name='caixa',
            name='diferenca',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='total_cartao_credito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='total_cartao_debito',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='total_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='total_entradas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='total_pix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='total_saidas',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario_abertura',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_abertos', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario_fechamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='caixas_fechados', to=settings.AUTH_USER_MODEL),
        ),
    ]
