# Generated by Django 5.1.6 on 2025-08-27 14:27

from django.db import migrations, models
from django.utils.timezone import now

class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0006_remove_caixa_usuario_caixa_diferenca_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tituloreceber',
            name='vencimento',
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='data_movimento',
            field=models.DateField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tituloreceber',
            name='data_vencimento',
            field=models.DateField(default=now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tituloreceber',
            name='situacao',
            field=models.CharField(
                choices=[('A', 'Aberto'), ('B', 'Baixado'), ('C', 'Cancelado')],
                default='A',
                max_length=1
            ),
        ),
    ]
