# Generated by Django 5.1.6 on 2025-09-03 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financeiro', '0007_remove_tituloreceber_vencimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caixa',
            name='saldo_atual',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
